import type { Metadata } from "next";
import "./globals.css";
import Toast from "./components/Toast";
import ToastProvider from "./context/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <ToastProvider>
          {children}

          <Toast />
        </ToastProvider>
      </body>
    </html>
  );
}
